const DL_API_PREFIX_KEY = 'dlapi_';
const ATTEMPTS_LIMIT = 50;
const ATTEMPT_DELAY = 100;
const DEFAULT_LANGUAGE = 'pl';
const BASIC_TAG = 'div';

export {
  ATTEMPTS_LIMIT,
  ATTEMPT_DELAY,
  DEFAULT_LANGUAGE,
  BASIC_TAG,
  DL_API_PREFIX_KEY,
};
